<script>
    require([
        'jquery',
    ], function($) {
        require([
            'Amasty_Blog/js/tag-it-custom'
        ], function() {
            $( document ).ready(function() {
                $("#posts_tags").tagit({
                    availableTags: <?= \Zend_Json::encode($block->getTagsNamesArray())?>
                });
                $("#posts_tags").data("ui-tagit").tagInput.addClass("fancy");
            });
        });
    });
</script>
